In [15]:
import pandas as pd

In [27]:
file_path = "第11屆平地原住民立法委員選舉候選人在臺北市各投開票所得票數一覽表.xlsx"
excel_file = pd.ExcelFile(file_path)
print(excel_file.sheet_names)

# 特定のシートをデータフレームに読み込む
sheet_name = excel_file.sheet_names[0]  # 最初のシート名を選択
df = excel_file.parse(sheet_name)
df_cleaned = df.dropna(how='all')
# df_cleaned = df_cleaned.drop(index=df_cleaned.index[0])


df_cleaned.head()

C:\Users\atsuk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['臺北市']

,第11屆平地原住民立法委員選舉候選人在臺北市各投開票所得票數一覽表,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,鄉(鎮、市、區)別,村里別,投開票所別,各候選人得票情形,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,有效票數A\nA=1+2+...+N,無效票數B,投票數C\nC=A+B,已領未投票數\nD\nD=E-C,發出票數E\nE=C+D,用餘票數F,選舉人數G\nG=E+F,投票率H\nH=C÷G
1,NaN,NaN,NaN,(1)\n高美珠\n無,(2)\n陳瑩\n民主進步黨,(3)\n陳國榮\n台灣維新,(4)\n陳政宗\n無,(5)\n忠仁．達祿斯\n無,(6)\n吳建智咖啡哥\n無,(7)\n黃仁\n中國國民黨,(8)\n米甘幹．理佛克\n新黨,(9)\n鄭天財 Sra‧Kacaw\n中國國民黨,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,總 計,NaN,NaN,366,1257,33,268,208,149,432,41,1940,4694,110,4804,2,4806,2554,7360,65.27
5,北投區,NaN,NaN,33,138,6,27,23,8,67,3,170,475,9,484,1,485,255,740,65.41
6,NaN,建民里,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00

In [29]:
# Excelファイルの読み込み
file_path = "第11屆平地原住民立法委員選舉候選人在臺北市各投開票所得票數一覽表.xlsx"
excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)
sheet_name = excel_file.sheet_names[0]
df = excel_file.parse(sheet_name)

df.iloc[1] = df.iloc[1].fillna(df.iloc[0])
df_cleaned = df.dropna(how='all')

# タイトル行の削除（2行目がデータの始まりと仮定）
df_cleaned = df_cleaned.iloc[1:]  # 1行目（インデックス0）を削除

# カラム名をデータの最初の行にリセット
df_cleaned.columns = df_cleaned.iloc[0]  # 現在の最初の行をカラム名に設定
df_cleaned = df_cleaned.iloc[1:]  # カラム名として使った行を削除

# 結果を確認
df_cleaned.head()

C:\Users\atsuk\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

['臺北市']

1,鄉(鎮、市、區)別,村里別,投開票所別,(1)\n高美珠\n無,(2)\n陳瑩\n民主進步黨,(3)\n陳國榮\n台灣維新,(4)\n陳政宗\n無,(5)\n忠仁．達祿斯\n無,(6)\n吳建智咖啡哥\n無,(7)\n黃仁\n中國國民黨,(8)\n米甘幹．理佛克\n新黨,(9)\n鄭天財 Sra‧Kacaw\n中國國民黨,有效票數A\nA=1+2+...+N,無效票數B,投票數C\nC=A+B,已領未投票數\nD\nD=E-C,發出票數E\nE=C+D,用餘票數F,選舉人數G\nG=E+F,投票率H\nH=C÷G
4,總 計,NaN,NaN,366,1257,33,268,208,149,432,41,1940,4694,110,4804,2,4806,2554,7360,65.27
5,北投區,NaN,NaN,33,138,6,27,23,8,67,3,170,475,9,484,1,485,255,740,65.41
6,NaN,建民里,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00
7,NaN,建民里,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00
8,NaN,建民里,3,0,3,0,0,0,0,2,0,3,8,1,9,0,9,4,13,69.23

In [14]:
df_cleaned = df.drop(columns=[col for col in df.columns if "nan" in col])

# Attempt to convert all columns except "鄉(鎮、市、區)別" and "村里別" to numeric types
for col in df_cleaned.columns:
    if col not in ["鄉(鎮、市、區)別", "村里別"]:
        df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce')

# Display the cleaned DataFrame and check for remaining non-numeric columns
df_cleaned.info()
df_cleaned.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1781 entries, 0 to 1780
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   第11屆平地原住民立法委員選舉候選人在臺北市各投開票所得票數一覽表  0 non-null      float64
 1   Unnamed: 1                         0 non-null      float64
 2   Unnamed: 2                         1764 non-null   float64
 3   Unnamed: 3                         1777 non-null   float64
 4   Unnamed: 4                         1777 non-null   float64
 5   Unnamed: 5                         1777 non-null   float64
 6   Unnamed: 6                         1777 non-null   float64
 7   Unnamed: 7                         1777 non-null   float64
 8   Unnamed: 8                         1777 non-null   float64
 9   Unnamed: 9                         1777 non-null   float64
 10  Unnamed: 10                        1777 non-null   float64
 11  Unnamed: 11                        1777 non-null   float64
 12  Unnamed: 12                        1777 non-null   float64
 13  Unnamed: 13                        1777 non-null   float64
 14  Unnamed: 14                        1777 non-null   float64
 15  Unnamed: 15                        1777 non-null   float64
 16  Unnamed: 16                        1777 non-null   float64
 17  Unnamed: 17                        1777 non-null   float64
 18  Unnamed: 18                        1777 non-null   float64
 19  Unnamed: 19                        1777 non-null   float64
dtypes: float64(20)
memory usage: 278.4 KB

,第11屆平地原住民立法委員選舉候選人在臺北市各投開票所得票數一覽表,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,366.0,1257.0,33.0,268.0,208.0,149.0,432.0,41.0,1940.0,4694.0,110.0,4804.0,2.0,4806.0,2554.0,7360.0,65.27